// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IUdWdhAhIUaUYP0aWKmwgjMkZRzSwME',
    appId: '1:562102601805:android:b6e34f88d2b7f1ff397404',
    messagingSenderId: '562102601805',
    projectId: 'jovera-finance-3021c',
    storageBucket: 'jovera-finance-3021c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qDt_vqm7OW5vNSQRRz_dnR_U6nT5mhk',
    appId: '1:562102601805:ios:a571c0a3e562d043397404',
    messagingSenderId: '562102601805',
    projectId: 'jovera-finance-3021c',
    storageBucket: 'jovera-finance-3021c.firebasestorage.app',
    androidClientId: '562102601805-avbicon3be5524h7luhege176vpp3m0c.apps.googleusercontent.com',
    iosClientId: '562102601805-dbb8t7hdjnl89fq0veegkq5g4t6ff96m.apps.googleusercontent.com',
    iosBundleId: 'com.joveragroup.finance',
  );

}